Interceptor added to retrofit client #25
moallemi/Film-Time pull request #26
Opened 2023-11-09 08:45 UTC by Sobhan-mp

2023-11-09 08:53 UTC, Sobhan-mp commented
Closes #25

2023-11-12 10:11 UTC, hadi-norouzi commented on data/network/src/main/java/io/filmtime/data/network/NetworkModule.kt
> +      1 to ApiKeyInterceptor()
I think it's better to provide different interceptor instances by annotation classes

2023-11-13 01:28 UTC, moallemi requested changes
Thanks for your contribution @Sobhan-mp. Please review the comments and apply the changes. Do not forget to format code as mentioned in [README](https://github.com/moallemi/Film-Time#code-style)

2023-11-13 01:28 UTC, moallemi commented on data/network/src/main/java/io/filmtime/data/network/TmdbMoviesService.kt
> +    @Path("movie_id") movieId: Int
Please do not remove trailing commas
```suggestion
    @Path("movie_id") movieId: Int,
```

2023-11-13 01:28 UTC, moallemi commented on data/network/src/main/java/io/filmtime/data/network/TmdbMoviesService.kt
> +    @Path("list_type") listType: String
Please do not remove trailing commas
```suggestion
    @Path("list_type") listType: String,
```

2023-11-13 01:28 UTC, moallemi commented on data/network/src/main/java/io/filmtime/data/network/TmdbShowsService.kt
> +    @Path("series_id") seriesId: Int
Same about trailing commas
```suggestion
    @Path("series_id") seriesId: Int,
```

2023-11-13 01:28 UTC, moallemi commented on data/network/src/main/java/io/filmtime/data/network/TmdbShowsService.kt
> +    @Path("time_window") timeWindow: String
same about trailing commas 
```suggestion
    @Path("time_window") timeWindow: String,
```

2023-11-13 01:28 UTC, moallemi commented on data/network/src/main/java/io/filmtime/data/network/NetworkModule.kt
> +      1 to ApiKeyInterceptor()
As @hadi-norouzi mentioned please use annotation class e.g: ForTmdb

```suggestion
  @ForTmdb
  @Provides
  @Singleton
  fun providesTmdbInterceptor(): Interceptor {
    return ...
```

2023-11-13 01:28 UTC, moallemi commented on data/network/src/main/java/io/filmtime/data/network/interceptor/ApiKeyInterceptor.kt
> +class ApiKeyInterceptor : Interceptor {
Please rename it to `TmdbApiKeyInterceptor` since we might have other APIs that required this manipulation

2023-11-23 07:25 UTC, Sobhan-mp commented
@hadi-norouzi @moallemi  Thank you both for your comments. I have updated my branch with adding required changes.
Please take a look...

2023-11-30 15:32 UTC, Sobhan-mp commented
Hi @moallemi , Are there any problems? Since you haven't accepted my pr yet...
Please provide feedbacks if you've found any problems in my code.
Thank you

2023-12-01 02:08 UTC, moallemi approved these changes
@Sobhan-mp Thanks for your contribution 🙏

2023-12-01 02:09 UTC, merged